#! /bin/bash

RADIO_ASR_DIR="/export/radio-asr.git"
CONDA_ENV_DIR="/export/conda-environments/nemo-1.3.0"

source /etc/profile.d/conda.sh
conda activate ${CONDA_ENV_DIR}
cd ${RADIO_ASR_DIR}/gnuradio
gnuradio-companion gmrs_online_demo.grc

